#!/bin/bash
#
# lazymadaga (Shell Script)
# 
# Objetivo: Framework para escrita de programas para o pacote Madagascar.
# 
# Site: https://dirack.github.io
# 
# Versão 1.3.0
# 
# Programador: Rodolfo A C Neves (Dirack) 19/04/2020
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

# Biblioteca de funções para formatar a mensagem de ajuda
source mensagemAjuda.sh 

# Biblioteca de funções para formatar a mensagem de erro
source mensagemErro.sh

## Verificar se o usuário forneceu $1
if [ -z "$1" ]
then
	MENSAGEMERRO="Usuário não ofereceu parâmetros ao programa!\nDigite $(basename $0) -h para obter ajuda!"
	exibirMensagemErroProgramaFormatada "$(basename $0)" "1" "$MENSAGEMERRO"
fi

# Versão deste programa
VERSAO="Shellinclude - 1.3.0"

## Variáveis que armazenam mensagem de ajuda do programa
NOME_PROGRAMA="$(basename $0)"
DESCRICAO="Gerar o template para um programa do pacote Madagascar que lê um arquivo 1D, 2D ou 3D."
PARAMETROS="-h --help::Exibe essa tela de ajuda e sai
-v --version::Exibe a versão do programa e sai
-1 ::Gerar template para 1D 
-2 ::Gerar template para 2D
-3 ::Gerar template para 3D"
EXEMPLO_DE_USO="~$ $(basename $0) -1 programa.c
\t~$ $(basename $0) -2 programa.c
\t~$ $(basename $0) -3 programa.c
"

case "$1" in
	-h | --help) ## Exibe a ajuda
		clear
		exibirMensagemAjudaProgramaFormatada "$NOME_PROGRAMA" "$DESCRICAO" "$PARAMETROS" "$EXEMPLO_DE_USO"
		exit 0
	;;

	-v | --version) ## Exibe a versão do programa
		echo $VERSAO
		exit 0
	;;

	-1) ## Fazer programa Madagascar baseado em template 1D
		cat templates/1d.c
	;;

	-2) ## Fazer programa Madagascar baseado em template 2D
		cat templates/2d.c
	;;

	-3) ## Fazer programa Madagascar baseado em template 3D
		cat templates/3d.c
	;;

	*)
		MENSAGEMERRO="Opção $1 Desconhecida!\nDigite $(basename $0) -h para obter ajuda"
		exibirMensagemErroProgramaFormatada "$(basename $0)" "4" "$MENSAGEMERRO"
	;;
esac
