#!/bin/bash
#
# recipesInstall (Shell Script)
# 
# Objetivo: Instalar madagascar recipes na versão local do Madagascar.
# 
# Site: https://dirack.github.io
# 
# Versão 1.0
# 
# Programador: Rodolfo A C Neves (Dirack) 18/11/2020
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.



URL='https://raw.githubusercontent.com/ahay/src/master/book/Recipes/'
RECIPES='pefInterpolation kimodel velocityAnalysis'

for i in $RECIPES
do
	wget "${URL}${i}.py" -O "$RSFSRC/book/Recipes/${i}.py"
done

cd $RSFSRC && sudo scons install
